### ISSUE TITLE
OOD scores calculation

### ISSUE THREAD

**Issue by DuongVanKhoa0811** [uulm-mrm/mmood3d#2]
Hi, we are currently working on a project that involves Lidar-based out-of-distribution object detection, which aligns closely with the purpose of your recent paper. **Could you release the code used to evaluate the OOD scores**, specifically the metrics AUROC, FPR95, AUPR-S, and AUPR-E. Access to this code would greatly assist us in calculating baseline results and advancing our study.

**Comment by TheCodez** [comment]
Code can be found here:
https://github.com/uulm-mrm/mmood3d/blob/main/mmood3d/evaluation/functional/ood_eval.py
https://github.com/uulm-mrm/mmood3d/blob/main/mmood3d/evaluation/metrics/ood_metric.py
