### ISSUE TITLE
Not find pre-trained model

### ISSUE THREAD

**Issue by ZhuShiyun** [uulm-mrm/mmood3d#3]
Hello authors!
I am trying to learning your projects, unluckily, the pre-trained models seems not be available.
Could u please upload them?
Cheers!

**Comment by ZhuShiyun** [comment]
Great! I found them in this link:[https://github.com/uulm-mrm/mmood3d/releases/](https://github.com/uulm-mrm/mmood3d/releases/)

**Comment by TheCodez** [comment]
Note that this is only the base CenterPoint detector. To get the OOD detector, you have to do your own training using the provided checkpoint.
If you have any other questions, feel free to ask them.

**Comment by ZhuShiyun** [comment]
Thank you for your notes, which is very important for us!^_^
